arch: x86_64
system-ghc: false

flags:
  encoding:
    systemencoding: false

#ghc-options:
#  '*': -Wall -prof

packages:
- '.'
extra-deps:
- digestive-functors-heist-0.8.6.2
- digestive-functors-snap-0.6.1.3
- encoding-0.8
- fast-tagsoup-1.0.7
- readable-0.3.1
- snap-extras-0.11.0.1
- snap-loader-static-0.9.0.2
- tagged-0.8.6
resolver: lts-3.8
#extra-include-dirs:
#- C:\Users\ubear\Documents\coding\libss
#- C:\Users\ubear\Documents\coding\libs\icu\include
#- C:\Users\ubear\Documents\coding\libs\pcre-8.33\inc
#extra-lib-dirs:
#- C:\Users\ubear\Documents\coding\libss
#- C:\Users\ubear\Documents\coding\libs\icu\bin64
#- C:\Users\ubear\Documents\coding\libs\pcre-8.33\lib\x64
