arch: x86_64
system-ghc: false

flags:
  encoding:
    systemencoding: false

#ghc-options:
#  '*': -Wall -prof

packages:
- '.'
extra-deps:
- digestive-functors-heist-0.8.6.2
- digestive-functors-snap-0.6.1.3
- encoding-0.8
- fast-tagsoup-1.0.7
- readable-0.3.1
- snap-extras-0.11.0.1
- snap-loader-static-0.9.0.2
- tagged-0.8.6
- git: https://github.com/RikvanToor/text-icu.git # Use a patched version of text-icu 
  commit: e1da5ba89c8794861f7ad773702f4792beb315bf

resolver: lts-3.8
